version: '3'

services:
  upload-service:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    deploy:
      replicas: 3
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - UPLOAD_ENV=${UPLOAD_ENV}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_UPLOAD_FOLDER=${CLOUDINARY_UPLOAD_FOLDER}
      - APP_PORT=${APP_PORT}