name: cd

env:
  CONTEXT_DIR: './'
  IMAGE_NAME: ${{ github.repository }}/staging
  DOCKER_REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create dotenv file
        run: |
          echo "
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}
          CLOUDINARY_UPLOAD_FOLDER=${{secrets.CLOUDINARY_UPLOAD_FOLDER}}
          UPLOAD_ENV=${{secrets.UPLOAD_ENV}}
          APP_PORT=${{secrets.APP_PORT}}
          " > .env

      - name: Preset Image Name
        run: |
          echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$(echo $(echo ${{$GITHUB_SHA-gitsha}} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
            registry: ${{ env.DOCKER_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.FULL_IMAGE_NAME }}

      - if: ${{ job.status == 'success'}}
        name: Send Message via Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.BOTTOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ✅ ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Build Status: ${{ job.status }}
            See New Build on: https://cdn.${{ secrets.SSH_HOST }}

            Good job!

      - if: ${{ job.status != 'success'}}
        name: Send Message via Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.BOTTOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ⛔️ There was an error when build project
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Build Status: ${{ job.status }}